
import "./globals.css";


export const metadata = {
	title: "Weather",
	description: "Generated by create next app",
	icons:{icon:"/weatherapp.svg"}

};

export default function RootLayout({ children }) {

	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
